#Review These
Overview on Decision Trees: https://www.datacamp.com/community/tutorials/decision-tree-classification-python

More on Encoding: https://pbpython.com/categorical-encoding.html

In [4]:
from sklearn import tree
import pandas as pd
import numpy

In [2]:
# Run this cell to download the dataset
!wget "https://archive.ics.uci.edu/ml/machine-learning-databases/00544/ObesityDataSet_raw_and_data_sinthetic%20(2).zip"
!unzip "/content/ObesityDataSet_raw_and_data_sinthetic (2).zip"

--2023-01-11 19:26:11--  https://archive.ics.uci.edu/ml/machine-learning-databases/00544/ObesityDataSet_raw_and_data_sinthetic%20(2).zip
Resolving archive.ics.uci.edu (archive.ics.uci.edu)... 128.195.10.252
Connecting to archive.ics.uci.edu (archive.ics.uci.edu)|128.195.10.252|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 119205 (116K) [application/x-httpd-php]
Saving to: ‘ObesityDataSet_raw_and_data_sinthetic (2).zip’

ObesityDataSet_raw_ 100%[===================>] 116.41K  --.-KB/s    in 0.08s

2023-01-11 19:26:11 (1.41 MB/s) - ‘ObesityDataSet_raw_and_data_sinthetic (2).zip’ saved [119205/119205]

Archive:  /content/ObesityDataSet_raw_and_data_sinthetic (2).zip
  inflating: ObesityDataSet_raw_and_data_sinthetic.arff
  inflating: ObesityDataSet_raw_and_data_sinthetic.csv

In [33]:
#import dataset as a pandas dataframe - name it df - using the .read_csv method
dataset = 'ObesityDataSet_raw_and_data_sinthetic.csv'
df = pd.read_csv(dataset)

In [6]:
#view first 5 rows of the dataset using the .head() method
df.head()

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [9]:
#check for the total amount of null values in each column using the .isnull() method
df.isnull().sum()

Gender                            0
Age                               0
Height                            0
Weight                            0
family_history_with_overweight    0
FAVC                              0
FCVC                              0
NCP                               0
CAEC                              0
SMOKE                             0
CH2O                              0
SCC                               0
FAF                               0
TUE                               0
CALC                              0
MTRANS                            0
NObeyesdad                        0
dtype: int64

Number of Columns

In [11]:
df.shape

(2111, 17)

Are there any new features that could be derived from our old features?

In [34]:
#create a function that takes your df as an input then calculates the BMI using the equation: BMI= Weight/ Height**2
def bmi(df):
  return df['Weight'] / df['Height'] ** 2

In [13]:
# apply the function to every row in the dataframe, create a new column, 'BMI' that contains those values. HINT: You can use .apply and lambda
df['BMI'] = bmi(df)

In [14]:
#check your dataframe
df.head()

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad,BMI
0,Female,21.0,1.62,64.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight,24.386526
1,Female,21.0,1.52,56.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight,24.238227
2,Male,23.0,1.80,77.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight,23.765432
3,Male,27.0,1.80,87.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I,26.851852
4,Male,22.0,1.78,89.8,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II,28.342381

Drop old features, i.e: height and weight

In [35]:
#use .drop() method to your dataframe, don't forget to set inplace=True
df.drop(['Weight', 'Height'],axis=1,  inplace=True)
df.head()

,Gender,Age,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,Female,21.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,0.0,1.0,no,Public_Transportation,Normal_Weight
1,Female,21.0,yes,no,3.0,3.0,Sometimes,yes,3.0,yes,3.0,0.0,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.0,yes,no,2.0,3.0,Sometimes,no,2.0,no,2.0,1.0,Frequently,Public_Transportation,Normal_Weight
3,Male,27.0,no,no,3.0,3.0,Sometimes,no,2.0,no,2.0,0.0,Frequently,Walking,Overweight_Level_I
4,Male,22.0,no,no,2.0,1.0,Sometimes,no,2.0,no,0.0,0.0,Sometimes,Public_Transportation,Overweight_Level_II

In [ ]:
#check your dataframe

In [36]:
#check your columns' data types using the .dtypes method
df.dtypes

Gender                             object
Age                               float64
family_history_with_overweight     object
FAVC                               object
FCVC                              float64
NCP                               float64
CAEC                               object
SMOKE                              object
CH2O                              float64
SCC                                object
FAF                               float64
TUE                               float64
CALC                               object
MTRANS                             object
NObeyesdad                         object
dtype: object

Check the unique values in your target label

In [37]:
df['NObeyesdad'].unique()

array(['Normal_Weight', 'Overweight_Level_I', 'Overweight_Level_II',
       'Obesity_Type_I', 'Insufficient_Weight', 'Obesity_Type_II',
       'Obesity_Type_III'], dtype=object)

Create two Dataframes of Features X and Output Y

In [38]:
y = df[['NObeyesdad']]
X = df.drop(['NObeyesdad'], axis=1)

In [39]:

X

,Gender,Age,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS
0,Female,21.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,0.000000,1.000000,no,Public_Transportation
1,Female,21.000000,yes,no,3.0,3.0,Sometimes,yes,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation
2,Male,23.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,2.000000,1.000000,Frequently,Public_Transportation
3,Male,27.000000,no,no,3.0,3.0,Sometimes,no,2.000000,no,2.000000,0.000000,Frequently,Walking
4,Male,22.000000,no,no,2.0,1.0,Sometimes,no,2.000000,no,0.000000,0.000000,Sometimes,Public_Transportation
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,Female,20.976842,yes,yes,3.0,3.0,Sometimes,no,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation
2107,Female,21.982942,yes,yes,3.0,3.0,Sometimes,no,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation
2108,Female,22.524036,yes,yes,3.0,3.0,Sometimes,no,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation
2109,Female,24.361936,yes,yes,3.0,3.0,Sometimes,no,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation
2110,Female,23.664709,yes,yes,3.0,3.0,Sometimes,no,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation

Change column name to something that makes sense

In [40]:
#replace newcolumname
y.rename(columns= {'NObeyesdad': 'obeisity_level '}, inplace= True)

/usr/local/lib/python3.8/dist-packages/pandas/core/frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

Encode your Catgorical Features

In [41]:
X_encoded = pd.get_dummies(X)
X_encoded.head()

,Age,FCVC,NCP,CH2O,FAF,TUE,Gender_Female,Gender_Male,family_history_with_overweight_no,family_history_with_overweight_yes,...,SCC_yes,CALC_Always,CALC_Frequently,CALC_Sometimes,CALC_no,MTRANS_Automobile,MTRANS_Bike,MTRANS_Motorbike,MTRANS_Public_Transportation,MTRANS_Walking
0,21.0,2.0,3.0,2.0,0.0,1.0,1,0,0,1,...,0,0,0,0,1,0,0,0,1,0
1,21.0,3.0,3.0,3.0,3.0,0.0,1,0,0,1,...,1,0,0,1,0,0,0,0,1,0
2,23.0,2.0,3.0,2.0,2.0,1.0,0,1,0,1,...,0,0,1,0,0,0,0,0,1,0
3,27.0,3.0,3.0,2.0,2.0,0.0,0,1,1,0,...,0,0,1,0,0,0,0,0,0,1
4,22.0,2.0,1.0,2.0,0.0,0.0,0,1,1,0,...,0,0,0,1,0,0,0,0,1,0

In [65]:
X_encoded.dtypes

Age                                   float64
FCVC                                  float64
NCP                                   float64
CH2O                                  float64
FAF                                   float64
TUE                                   float64
Gender_Female                           uint8
Gender_Male                             uint8
family_history_with_overweight_no       uint8
family_history_with_overweight_yes      uint8
FAVC_no                                 uint8
FAVC_yes                                uint8
CAEC_Always                             uint8
CAEC_Frequently                         uint8
CAEC_Sometimes                          uint8
CAEC_no                                 uint8
SMOKE_no                                uint8
SMOKE_yes                               uint8
SCC_no                                  uint8
SCC_yes                                 uint8
CALC_Always                             uint8
CALC_Frequently                         uint8
CALC_Sometimes                          uint8
CALC_no                                 uint8
MTRANS_Automobile                       uint8
MTRANS_Bike                             uint8
MTRANS_Motorbike                        uint8
MTRANS_Public_Transportation            uint8
MTRANS_Walking                          uint8
dtype: object

*Perform* label encoding to y

In [43]:
# run this cell to check your label column - y
y.columns

Index(['obeisity_level '], dtype='object')

In [56]:
# import preprocessing module from sklearn
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y_encoded = le.fit_transform(y)
y_encoded
#initialize label encoder
# fit the data to your initialized label encoder

array([1, 1, 1, ..., 4, 4, 4])

Normalize so that no feature has more weight over the other, you can use MinMaxScaler

In [66]:
#import scaler - you can use MinMaxScaler
from sklearn.preprocessing import MinMaxScaler

# Initialize a scaler, then apply it to the features
scaler = MinMaxScaler()
# Create a list of your numerical features
numerical = ['Age','FCVC', 'NCP', 'CH2O', 'FAF', 'TUE']

X_encoded[numerical] = scaler.fit_transform(X_encoded[numerical])

# Show an example of a record with scaling applied
display(X_encoded.head(n = 1))

,Age,FCVC,NCP,CH2O,FAF,TUE,Gender_Female,Gender_Male,family_history_with_overweight_no,family_history_with_overweight_yes,...,SCC_yes,CALC_Always,CALC_Frequently,CALC_Sometimes,CALC_no,MTRANS_Automobile,MTRANS_Bike,MTRANS_Motorbike,MTRANS_Public_Transportation,MTRANS_Walking
0,0.148936,0.5,0.666667,0.5,0.0,0.5,1,0,0,1,...,0,0,0,0,1,0,0,0,1,0

Shuffle and split the data using train_test_split

In [67]:
#import train_test_split from sklearn
from sklearn.model_selection import train_test_split as tts
# Split the 'features' and 'income' data into training and testing sets

X_train, X_test, y_train, y_test = tts(X_encoded, y_encoded) 

# Show the results of the split
print ("Training set has {} samples.".format(X_train.shape[0]))
print ("Testing set has {} samples.".format(X_test.shape[0]))

Training set has 1583 samples.
Testing set has 528 samples.

# Training, Prediction and Evaluation.
Choose a classifier: you can use logistic regression, NaiveBayes, SVM, KNN, Decision Trees, Random Forrest.

In [80]:
# Let's use Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier

from sklearn.model_selection import GridSearchCV
from sklearn.metrics import make_scorer , f1_score
# import SVM Classifier from Sklearn
# initilize the classifier
params = {'max_depth' : [3, 4, 5, 7, 9 , 12 , 12 , 15 , 20], 'min_samples_leaf' : [10, 20 , 30 ] , 'min_samples_split' : [1, 2, 5, 10]}
ms = make_scorer(f1_score)
model = GridSearchCV(DecisionTreeClassifier(), params)
# fit your classifier to the data using the .fit() method
model.fit(X_train, y_train)
# predict train set values
pred_train = model.predict(X_train)
# predict test set values
pred_test = model.predict(X_test)

/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py:372: FitFailedWarning:
135 fits failed out of a total of 540.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
135 fits failed with the following error:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_validation.py", line 680, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/usr/local/lib/python3.8/dist-packages/sklearn/tree/_classes.py", line 937, in fit
    super().fit(
  File "/usr/local/lib/python3.8/dist-packages/sklearn/tree/_classes.py", line 250, in fit
    raise ValueError(
ValueError: min_samples_split must be an integer greater than 1 or a float in (0.0, 1.0]; got the integer 1

  warnings.warn(some_fits_failed_message, FitFailedWarning)
/usr/local/lib/python3.8/dist-packages/sklearn/model_selection/_search.py:969: UserWarning: One or more of the test scores are non-finite: [       nan 0.4750609  0.4750609  0.4750609         nan 0.4750609
 0.4750609  0.4750609         nan 0.47253324 0.47253324 0.47253324
        nan 0.54202172 0.54202172 0.54202172        nan 0.5312802
 0.5312802  0.5312802         nan 0.52622489 0.52622489 0.52622489
        nan 0.59763008 0.59763008 0.59763008        nan 0.58370603
 0.58370603 0.58370603        nan 0.56224294 0.56224294 0.56224294
        nan 0.64878409 0.65067684 0.65193867        nan 0.61086132
 0.61086132 0.61086132        nan 0.57677195 0.57677195 0.57677195
        nan 0.66835443 0.66835443 0.66519986        nan 0.62223575
 0.62223575 0.62223575        nan 0.58497384 0.58497384 0.58497384
        nan 0.67910594 0.68099868 0.67657829        nan 0.62286667
 0.62286667 0.62286667        nan 0.5830811  0.5830811  0.5830811
        nan 0.67784012 0.67594737 0.67657829        nan 0.62286667
 0.62286667 0.62286667        nan 0.5830811  0.5830811  0.5830811
        nan 0.67847103 0.68099868 0.67657829        nan 0.62286667
 0.62286667 0.62286667        nan 0.5830811  0.5830811  0.5830811
        nan 0.67973286 0.67847103 0.67910594        nan 0.62286667
 0.62286667 0.62286667        nan 0.5830811  0.5830811  0.5830811 ]
  warnings.warn(

Import our evaluation metric

In [81]:
# import accuracy_score from sklearn
from sklearn.metrics import accuracy_score
# check accuracy on training set
acc_train = accuracy_score(y_train, pred_train)
# check accuracy on testing set
acc_test = accuracy_score(y_test, pred_test)

print(acc_train)
print(acc_test)

0.7883765003158559
0.6856060606060606

In [71]:
# visualize your tree
 tree.plot_tree(classifier)

IndentationError: ignored

In [ ]:
# check the hyperparameters used
classifier.get_params(deep=True)

In [ ]:
# check your tree's depth
classifier.get_depth()

# Reflect on your results